trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/WebApi/*
      - src/Application/*
      - src/Domain/*
      - src/Infrastructure/*
      - src/Common/*
      - src/UnitTest/*
      - src/IntegrationTest/*

variables:
  - name: ProjectName
    value: "WebApi"
  - name: ArtifactName
    value: "WebApi"
  - name: UnitTestProjects
    value: "**/UnitTest.csproj"
  - name: IntegrationTestProjects
    value: "**/IntegrationTest.csproj"

parameters:
  - name: slotName
    displayName: 'Custom Slot Name'
    type: string
    default: ''  # Empty by default; if not provided, branch name will be used
  - name: deployToFeatureSlot
    displayName: 'Deploy to Feature Slot'
    type: boolean
    default: true  # Default to true, can be set to false in the UI

name: WebApi_$(Date:yyyy) -$(Date:dd)$(Rev:.r)--$(Build.SourceBranchName)

stages:
  - stage: Build_And_Tests
    jobs:
      - job: Build
        pool:
          vmImage: "windows-latest"
        steps:
          - template: templates/build-dot-net.yml
            parameters:
              projectPath: "src/$(ProjectName)"
              artifactName: "$(ArtifactName)"

      - job: Unit_Tests
        pool:
          vmImage: "windows-latest"
        steps:
          - template: templates/test-dot-net.yml
            parameters:
              testProjects: "$(UnitTestProjects)"

      - job: Integration_Tests
        pool:
          vmImage: "windows-latest"
        steps:
          - template: templates/test-dot-net.yml
            parameters:
              testProjects: "$(IntegrationTestProjects)"
